import Head from "next/head";

import {
  Flex,
  Box,
  Stack,
  Heading,
  useColorModeValue,
  Button,
  Checkbox,
  Link,
  useDisclosure,
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalCloseButton,
  ModalBody,
  FormControl,
  FormLabel,
  Input,
  ModalFooter,
} from "@chakra-ui/react";
import { useRouter } from "next/router";
import { MouseEvent, useState } from "react";
import { auth, db } from "../../firebase";
import { useRecoilState} from "recoil";
import { emailState, passwordState } from "@/Recoil/atom";
import {
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
} from "firebase/auth";
import { createEmailState, createPasswordState } from "../Recoil/atom";
import { doc, setDoc } from "firebase/firestore";

// ログインページ
export default function Login() {
  const router = useRouter();
  // ログイン情報
  const [email, setEmail] = useRecoilState<string>(emailState);
  const [password, setPassword] = useRecoilState<string>(passwordState);

  const [error, setError] = useState<unknown>("");

  // サインアップ情報
  const [createEmail, setCreateEmail] =
    useRecoilState<string>(createEmailState);
  const [createPassword, setCreatePassword] =
    useRecoilState<string>(createPasswordState);

  const { isOpen, onOpen, onClose } = useDisclosure();

  // メールアドレスとパスワードでログイン
  const handleLogin = async (e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    try {
      await signInWithEmailAndPassword(auth, email, password);
      setEmail("");
      setPassword("");
      router.push("/home");
    } catch (error: unknown) {
      setError(error);
    }
  };

  const handleSignUp = async (e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault();
    try {
      await createUserWithEmailAndPassword(auth, createEmail, createPassword);
      setCreateEmail("");
      setCreatePassword("");
      // ユーザをFirestoreに保存する
      const user = auth.currentUser;
      const usersRef = doc(db, "users", user!.uid);
      await setDoc(usersRef, {
        id: user!.uid,
        email: createEmail,
      });
      router.push("/home");
    } catch (error: unknown) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Ohung</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Flex
        minH={"100vh"}
        align={"center"}
        justify={"center"}
        bg={useColorModeValue("gray.50", "gray.800")}
        pb={{ base: "72px" }}
      >
        <Stack spacing={8} mx={"auto"} maxW={"lg"} py={12} px={6}>
          <Stack align={"center"}>
            <Heading fontSize={"4xl"}>サインイン</Heading>
            {/* クリエイト */}
            <Button onClick={onOpen}>新規作成はこちら</Button>

            <Modal isOpen={isOpen} onClose={onClose}>
              <ModalOverlay />
              <ModalContent>
                <ModalHeader>新規作成</ModalHeader>
                <ModalCloseButton />
                <ModalBody pb={6}>
                  <FormControl>
                    <FormLabel>メールアドレス</FormLabel>
                    <Input
                      id="email"
                      type="email"
                      value={createEmail}
                      onChange={(event) => setCreateEmail(event.target.value)}
                      placeholder="メールアドレス"
                    />
                    <FormLabel>パスワード</FormLabel>
                    <Input
                      id="password"
                      type="password"
                      value={createPassword}
                      onChange={(event) =>
                        setCreatePassword(event.target.value)
                      }
                      placeholder="パスワード"
                    />
                  </FormControl>
                </ModalBody>

                <ModalFooter>
                  <Button onClick={handleSignUp} colorScheme="blue" mr={3}>
                    作成
                  </Button>
                  <Button onClick={onClose}>戻る</Button>
                </ModalFooter>
              </ModalContent>
            </Modal>
          </Stack>
          <Box
            rounded={"lg"}
            bg={useColorModeValue("white", "gray.700")}
            boxShadow={"lg"}
            p={8}
          >
            <Stack spacing={4}>
              {/* <MailInput /> */}
              <FormControl>
                <FormLabel>メールアドレス</FormLabel>
                <Input
                  id="mail"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                />
                <FormLabel>パスワード</FormLabel>
                <Input
                  id="pass"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                />
              </FormControl>
              <Stack spacing={10}>
                <>
                <Stack
                  direction={{ base: "column", sm: "row" }}
                  align={"start"}
                  justify={"space-between"}
                  >
                  <Checkbox>Remember me</Checkbox>
                  <Link color={"blue.400"}>Forgot password?</Link>
                </Stack>
                <Button
                  onClick={handleLogin}
                  bg={"blue.400"}
                  color={"white"}
                  _hover={{
                    bg: "blue.500",
                  }}
                  >
                  Sign in
                </Button>
                {error && (
                  <Box
                  bg="red.100"
                  color="red.500"
                  p="2"
                  rounded="md"
                  fontSize="sm"
                  textAlign={"center"}
                  >
                    サインインに失敗しました
                  </Box>
                )}
                </>
              </Stack>
            </Stack>
          </Box>
        </Stack>
      </Flex>
    </>
  );
}
