import Head from "next/head";

import { Flex, Box, Stack, Heading, useColorModeValue } from "@chakra-ui/react";
import MailInput from "@/components/atoms/LoginPage/MailInput";
import PasswordInput from "../components/atoms/LoginPage/PasswordInput";
import RemFor from "@/components/molucules/LoginPage/RemFor";
import { useRouter } from "next/router";

// ログインページ
export default function Login() {
  const router= useRouter();

  return (
    <>
      <Head>
        <title>Ohung</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Flex
        minH={"100vh"}
        align={"center"}
        justify={"center"}
        bg={useColorModeValue("gray.50", "gray.800")}
      >
        <Stack spacing={8} mx={"auto"} maxW={"lg"} py={12} px={6}>
          <Stack align={"center"}>
            <Heading fontSize={"4xl"}>Sign in to your account</Heading>
          </Stack>
          <Box
            rounded={"lg"}
            bg={useColorModeValue("white", "gray.700")}
            boxShadow={"lg"}
            p={8}
          >
            <Stack spacing={4}>
              <MailInput />
              <PasswordInput />
              <RemFor />
            </Stack>
          </Box>
        </Stack>
      </Flex>
    </>
  );
}
